definitions:
  echo.HTTPError:
    properties:
      message: {}
    type: object
  model.ContaContabil:
    properties:
      codigo:
        type: string
      nome:
        type: string
    type: object
info:
  contact:
    email: cgpre@planejamento.rr.gov.br
    name: Equipe da CGPRE (SEPLAN/RR)
  description: API para consulta de dados e relatórios do FIPLAN em JSON
  title: API do FIPLAN
  version: 0.0.0-alpha
paths:
  /conta:
    get:
      consumes:
      - application/json
      description: Teste
      parameters:
      - description: Ano de Exercício
        in: query
        name: ano_exercicio
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.ContaContabil'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Lista as contas
      tags:
      - Conta
swagger: "2.0"
